- ignore:
    name: "Redundant bracket"
    within:
      - "Functional.Prelude"
      - "Functional.Prelude.FuncEnv"
      - "Integration.Charon.natToInt"
      - "Charon.Data.PathData"
      - "Charon.Data.PathData.Common"
      - "Charon.Data.PathData.Internal"
      - "Charon.Data.Paths.applyPathI"
      - "Charon.Data.Paths.liftPathIF"
      - "Charon.Data.Paths.liftPathIF'"
      - "Charon.Runner"
      - "Charon.Runner.Args.unsafeNE"
      - "Test.Utils.clearDirectory"
      - "Test.Utils.exToBuilder"
      - "Test.Utils.unsafeReplaceDir"
- ignore:
    name: "Use bimap"
    within:
      # The warning is spurious as Bifunctor is not polykinded
      - "Integration.Charon"
- ignore:
    name: "Use <$>"
    within: "Charon.Runner.Args.TH"
- ignore:
    name: "Redundant ^."
    within: "Charon.Runner.Merged"
