- ignore:
    name: "Redundant bracket"
    within:
      - "Integration.SafeRm.natToInt"
      - "SafeRm.Data.PathData"
      - "SafeRm.Data.Paths.applyPathI"
      - "SafeRm.Data.Paths.liftPathIF"
      - "SafeRm.Data.Paths.liftPathIF'"
      - "SafeRm.Runner"
      - "SafeRm.Runner.Args.unsafeNE"
      - "Test.Utils.clearDirectory"
      - "Test.Utils.exToBuilder"
      - "Test.Utils.unsafeReplaceDir"