- ignore:
    name: "Redundant bracket"
    within:
      - "Functional.Prelude"
      - "Functional.Prelude.FuncEnv"
      - "Integration.SafeRm.natToInt"
      - "SafeRm.Data.PathData"
      - "SafeRm.Data.PathData.Common"
      - "SafeRm.Data.PathData.Internal"
      - "SafeRm.Data.Paths.applyPathI"
      - "SafeRm.Data.Paths.liftPathIF"
      - "SafeRm.Data.Paths.liftPathIF'"
      - "SafeRm.Runner"
      - "SafeRm.Runner.Args.unsafeNE"
      - "Test.Utils.clearDirectory"
      - "Test.Utils.exToBuilder"
      - "Test.Utils.unsafeReplaceDir"
- ignore:
    name: "Use bimap"
    within:
      # The warning is spurious as Bifunctor is not polykinded
      - "Integration.SafeRm"