resolver: nightly-2022-10-11
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
    -Wno-unticked-promoted-constructors -Wprepositive-qualified-module
extra-deps:
- env-guard-0.2@sha256:feaecb437c597537dbef656300068c50a97e28ae83a8b63426ee14a1413207f5,1312
- package-version-0.2@sha256:b326d1af39fb3960846fcb3e4dc73d8f51c3bedbf1c08ca97c086462de829519,2781
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2c8a79e8d3bf67c99e4851c557bf68a44c512307
- git: https://github.com/tbidne/bounds.git
  commit: 004f03aec46f29069fd0bf5115a384cd2b3141b3
- git: https://github.com/tbidne/byte-types.git
  commit: be3e764d76c530fd3641c133ed2d53adfc8f046d
- git: https://github.com/tbidne/monad-effects.git
  commit: 3fddc571755e7b01a0c665058e9e0503b5c07250
  subdirs:
  - monad-callstack
  - monad-fs
  - monad-logger-namespace
  - monad-terminal
  - monad-time
- git: https://github.com/tbidne/path-size.git
  commit: 5d37dfae28189a75d2c62df4c62e47081be81db4
nix:
  shell-file: nix/stack.nix
