# Path to the trash home. Overridden by the CLI -t option. Defaults to
# ~/.trash
trash-home = "./tmp"

# File log level. Can be one of none, error, warn, info, or debug.
# Defaults to none.
log-level = "info"