name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.4"]
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build

      - name: unit Tests
        run: cabal test unit --test-options '--max-runs 10000'

      - name: Config Tests
        run: cabal test config

      - name: Functional Tests
        run: cabal test functional