name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.4.4"
        platform:
          - os: "macos-latest"
            set-env: "export"
            trials: 1000
          - os: "ubuntu-latest"
            set-env: "export"
            trials: 10000
          - os: "windows-latest"
            set-env: "set"
            trials: 100
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: haskell/actions/setup@v2.3.4
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: cabal configure --enable-tests --enable-benchmarks

      - name: Compile
        run: cabal build safe-rm:exe:safe-rm

      - name: Unit Tests
        run: cabal test unit --test-options '--hedgehog-tests ${{ matrix.platform.trials }}'

      - name: Integration Tests
        run: |
          ${{ matrix.platform.set-env }} INT_LOGS=1
          cabal test integration --test-options '--hedgehog-tests ${{ matrix.platform.trials }}'

      - name: Functional Tests
        run: cabal test functional

      - name: Benchmarks
        if: ${{ matrix.platform.os == 'ubuntu-latest' }}
        id: bench
        run: |
          cabal bench --benchmark-options '
            --csv benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.csv
            --svg benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.svg
            --baseline benchmarks/baseline_${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.csv
            --fail-if-slower 50
            --fail-if-faster 50'

      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.bench.conclusion == 'failure' }}
        with:
          name: build-artifacts
          path: |
            benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.csv
            benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.svg