name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
        - "9.2.5"
        - "9.4.4"
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build

      - name: Unit Tests
        run: cabal test unit --enable-tests --test-options '--hedgehog-tests 10000'

      - name: Integration Tests
        run: cabal test integration --enable-tests --test-options '--hedgehog-tests 10000'

      - name: Functional Tests
        run: cabal test functional --enable-tests

      - name: Benchmarks
        run: |
          set +e

          cabal bench --benchmark-options '
            --csv benchmarks/bench_ci.csv
            --baseline benchmarks/baseline_ci.csv
            --fail-if-slower 10'

          bench_ec=$?

          cat benchmarks/bench_ci.csv

          exit $bench_ec