name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.4.4"
        os:
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build

      - name: Unit Tests
        run: cabal test unit --enable-tests --test-options '--hedgehog-tests 10000'

      - name: Integration Tests
        run: cabal test integration --enable-tests --test-options '--hedgehog-tests 10000'

      - name: Functional Tests
        run: cabal test functional --enable-tests

      - name: Benchmarks
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: bench
        run: |
          cabal bench --benchmark-options '
            --csv benchmarks/${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            --svg benchmarks/${{ matrix.os }}_${{ matrix.ghc }}_ci.svg
            --baseline benchmarks/baseline_${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            --fail-if-slower 20
            --fail-if-faster 20'

      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.bench.conclusion == 'failure' }}
        with:
          name: build-artifacts
          path: |
            benchmarks/${{ matrix.os }}_${{ matrix.ghc }}_ci.csv
            benchmarks/${{ matrix.os }}_${{ matrix.ghc }}_ci.svg